
ccflags-y +=-Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-result
ccflags-y += -I${KERNEL_PATH}/drivers/soc/cvitek/include/common/kapi/
obj-$(CONFIG_CVI_RTOS_CMDQU) += rtos_cmdqu.o cvi_spinlock.o
rtos_cmdqu-objs =  rtos_cmdqu.o cvi_spinlock.o


