# Cvitek Platform Support
obj-$(CONFIG_SND_CVITEK_I2S) += plat_i2s.o
obj-$(CONFIG_SND_CVITEK_I2S_SUBSYS) += plat_i2s_subsys.o

# Cvitek PDM
obj-$(CONFIG_SND_SOC_CVITEK_PDM) += codec_pdm.o
obj-$(CONFIG_SND_SOC_CVITEK_CARD_PDM) += card_pdm.o

#Cvitek ADC
obj-$(CONFIG_SND_SOC_CVITEK_ADC) += codec_adc.o
obj-$(CONFIG_SND_SOC_CVITEK_CARD_ADC) += card_adc.o

#Cvitek DAC
obj-$(CONFIG_SND_SOC_CVITEK_DAC) += codec_dac.o
obj-$(CONFIG_SND_SOC_CVITEK_CARD_DAC) += card_dac.o

#other
obj-$(CONFIG_SND_SOC_CVITEK_CODEC_DUMMY) += codec_dummy.o
obj-$(CONFIG_SND_SOC_CVITEK_CARD_DUMMY) += card_ext.o

