# Makefile for the focaltech touchscreen drivers.
obj-$(CONFIG_TOUCHSCREEN_FTS) += fts_ts.o

fts_ts-objs	+=  focaltech_core.o
fts_ts-objs	+=  focaltech_ex_fun.o
fts_ts-objs	+=  focaltech_ex_mode.o
fts_ts-objs	+=  focaltech_gesture.o
fts_ts-objs	+=  focaltech_esdcheck.o
fts_ts-objs	+=  focaltech_point_report_check.o
fts_ts-objs	+=  focaltech_proximity.o
fts_ts-objs	+=  tpd.o

fts_ts-objs	+=  focaltech_flash.o
fts_ts-objs	+=  focaltech_flash/
fts_ts-objs	+=  focaltech_flash/focaltech_upgrade_ft6336u.o

fts_ts-objs	+=  focaltech_i2c.o
